import type { Lead } from "@/lib/domain/lead";

export const demoLeads: Lead[] = [
  {
    id: "demo-1",
    userId: null,
    tenantId: "demo",
    createdAt: "2026-07-27T15:20:00.000Z",
    fullName: "Valentina Rojas",
    phone: "+57 315 204 8890",
    carModel: "V3",
    carModels: ["V3"],
    timeframe: "INMEDIATA",
    paymentMethod: "CREDITO",
    tradeInCar: true,
    score: 100,
    temperature: "HIGH",
    notes: "Busca una SUV para uso familiar. Tiene vehículo para retoma.",
    whatsappStatus: "SENT",
    conversationState: "WAITING_CUSTOMER",
    nextActionAt: null,
    nextActionType: null,
    lastActivityAt: "2026-07-27T15:30:00.000Z",
    lastCustomerMessageAt: null,
    lastAgentMessageAt: "2026-07-27T15:30:00.000Z",
    lastCustomerMessagePreview: null,
    lastMessageDirection: "OUTBOUND",
    lastMessagePreview: "Hola Valentina, soy tu asesor. Gracias por visitarnos.",
    lastInboundMessageId: null,
    lastInboundMessageAt: null,
    lastInboundMessagePreview: null,
    inboundClassification: null,
    inboundManualDecision: null,
    deletedAt: null,
    status: "NUEVO",
    followUpActions: [],
  },
  {
    id: "demo-2",
    userId: null,
    tenantId: "demo",
    createdAt: "2026-07-27T13:05:00.000Z",
    fullName: "Andrés Molina",
    phone: "+57 300 710 4421",
    carModel: "CS75",
    carModels: ["CS75"],
    timeframe: "1_3_MESES",
    paymentMethod: "LEASING",
    tradeInCar: false,
    score: 88,
    temperature: "HIGH",
    notes: "Pidió comparar cuota mensual y versiones.",
    whatsappStatus: "PENDING",
    conversationState: "NEW",
    nextActionAt: null,
    nextActionType: null,
    lastActivityAt: null,
    lastCustomerMessageAt: null,
    lastAgentMessageAt: null,
    lastCustomerMessagePreview: null,
    lastMessageDirection: null,
    lastMessagePreview: null,
    lastInboundMessageId: null,
    lastInboundMessageAt: null,
    lastInboundMessagePreview: null,
    inboundClassification: null,
    inboundManualDecision: null,
    deletedAt: null,
    status: "CONTACTADO",
    followUpActions: [],
  },
  {
    id: "demo-3",
    userId: null,
    tenantId: "demo",
    createdAt: "2026-07-26T18:45:00.000Z",
    fullName: "Camilo Pérez",
    phone: "+57 318 991 0254",
    carModel: "HUNTER TURBO",
    carModels: ["HUNTER TURBO"],
    timeframe: "3_6_MESES",
    paymentMethod: "POR_DEFINIR",
    tradeInCar: false,
    score: 48,
    temperature: "MEDIUM",
    notes: "Está validando presupuesto con su pareja.",
    whatsappStatus: "SENT",
    conversationState: "WAITING_CUSTOMER",
    nextActionAt: null,
    nextActionType: null,
    lastActivityAt: "2026-07-26T19:00:00.000Z",
    lastCustomerMessageAt: null,
    lastAgentMessageAt: "2026-07-26T19:00:00.000Z",
    lastCustomerMessagePreview: null,
    lastMessageDirection: "OUTBOUND",
    lastMessagePreview: "Te envío la información solicitada sobre el Mazda 3.",
    lastInboundMessageId: null,
    lastInboundMessageAt: null,
    lastInboundMessagePreview: null,
    inboundClassification: null,
    inboundManualDecision: null,
    deletedAt: null,
    status: "COTIZADO",
    followUpActions: [],
  },
  {
    id: "demo-4",
    userId: null,
    tenantId: "demo",
    createdAt: "2026-07-25T16:12:00.000Z",
    fullName: "Sofía Vargas",
    phone: "+57 311 620 7712",
    carModel: "Otro modelo",
    carModels: ["Otro modelo"],
    timeframe: "EXPLORANDO",
    paymentMethod: "CONTADO",
    tradeInCar: false,
    score: 28,
    temperature: "LOW",
    notes: null,
    whatsappStatus: "FAILED",
    conversationState: "NEW",
    nextActionAt: null,
    nextActionType: null,
    lastActivityAt: null,
    lastCustomerMessageAt: null,
    lastAgentMessageAt: null,
    lastCustomerMessagePreview: null,
    lastMessageDirection: null,
    lastMessagePreview: null,
    lastInboundMessageId: null,
    lastInboundMessageAt: null,
    lastInboundMessagePreview: null,
    inboundClassification: null,
    inboundManualDecision: null,
    deletedAt: null,
    status: "NUEVO",
    followUpActions: [],
  },
];
