import type { Lead } from "@/lib/domain/lead";

export const demoLeads: Lead[] = [
  {
    id: "demo-1",
    userId: null,
    tenantId: "demo",
    createdAt: "2026-07-27T15:20:00.000Z",
    fullName: "Valentina Rojas",
    phone: "+57 315 204 8890",
    carModel: "Mazda CX-30",
    timeframe: "INMEDIATA",
    paymentMethod: "CREDITO",
    tradeInCar: true,
    score: 100,
    temperature: "HIGH",
    notes: "Busca una SUV para uso familiar. Tiene vehículo para retoma.",
    whatsappStatus: "SENT",
    status: "NUEVO",
  },
  {
    id: "demo-2",
    userId: null,
    tenantId: "demo",
    createdAt: "2026-07-27T13:05:00.000Z",
    fullName: "Andrés Molina",
    phone: "+57 300 710 4421",
    carModel: "Toyota Corolla Cross",
    timeframe: "1_3_MESES",
    paymentMethod: "LEASING",
    tradeInCar: false,
    score: 88,
    temperature: "HIGH",
    notes: "Pidió comparar cuota mensual y versiones.",
    whatsappStatus: "PENDING",
    status: "CONTACTADO",
  },
  {
    id: "demo-3",
    userId: null,
    tenantId: "demo",
    createdAt: "2026-07-26T18:45:00.000Z",
    fullName: "Camilo Pérez",
    phone: "+57 318 991 0254",
    carModel: "Mazda 3",
    timeframe: "3_6_MESES",
    paymentMethod: "POR_DEFINIR",
    tradeInCar: false,
    score: 48,
    temperature: "MEDIUM",
    notes: "Está validando presupuesto con su pareja.",
    whatsappStatus: "SENT",
    status: "COTIZADO",
  },
  {
    id: "demo-4",
    userId: null,
    tenantId: "demo",
    createdAt: "2026-07-25T16:12:00.000Z",
    fullName: "Sofía Vargas",
    phone: "+57 311 620 7712",
    carModel: "Otro modelo",
    timeframe: "EXPLORANDO",
    paymentMethod: "CONTADO",
    tradeInCar: false,
    score: 28,
    temperature: "LOW",
    notes: null,
    whatsappStatus: "FAILED",
    status: "NUEVO",
  },
];
